<<<<<<< HEAD
--<ScriptOptions statementTerminator=";"/>

CREATE TABLE CATALOGUE (
		CODE INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		NOM CHAR(20) NOT NULL,
		PRIX DOUBLE NOT NULL,
		STOCK INTEGER NOT NULL
	);

CREATE TABLE ADHERANT (
		ID_ADH INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		MDP CHAR(20) NOT NULL,
		NOM CHAR(20) NOT NULL,
		PRENOM CHAR(20) NOT NULL,
		ADRESSE CHAR(20) NOT NULL,
		CP CHAR(5) NOT NULL,
		VILLE CHAR(20) NOT NULL,
		PAYS CHAR(20) NOT NULL
	);

CREATE TABLE COMMANDE (
		CODE INTEGER,
		ID_ADH INTEGER,
		QUANTITE DOUBLE NOT NULL
	);

CREATE INDEX SQL140129140246650 ON COMMANDE (CODE ASC);

CREATE UNIQUE INDEX SQL140129135514500 ON ADHERANT (ID_ADH ASC);

CREATE INDEX SQL140129140246651 ON COMMANDE (ID_ADH ASC);

CREATE UNIQUE INDEX SQL140129135643580 ON CATALOGUE (CODE ASC);

ALTER TABLE ADHERANT ADD CONSTRAINT SQL140129135514500 PRIMARY KEY (ID_ADH);

ALTER TABLE CATALOGUE ADD CONSTRAINT SQL140129135643580 PRIMARY KEY (CODE);

ALTER TABLE COMMANDE ADD CONSTRAINT ID_ADH FOREIGN KEY (ID_ADH)
	REFERENCES ADHERANT (ID_ADH);

ALTER TABLE COMMANDE ADD CONSTRAINT CODE FOREIGN KEY (CODE)
	REFERENCES CATALOGUE (CODE);

=======
--<ScriptOptions statementTerminator=";"/>
     --drop table assoc.CATALOGUE;
     --drop table assoc.ADHERANT;
     --drop table assoc.COMMANDE;
CREATE TABLE assoc.CATALOGUE (
		CODE INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		NOM CHAR(20) NOT NULL,
		PRIX DOUBLE NOT NULL,
		STOCK INTEGER NOT NULL
	);
	
CREATE TABLE assoc.ADHERANT (
		ID_ADH CHAR(20) NOT NULL,
		MDP CHAR(20) NOT NULL,
		NOM CHAR(20) NOT NULL,
		PRENOM CHAR(20) NOT NULL,
		ADRESSE CHAR(60) NOT NULL,
		CP CHAR(5) NOT NULL,
		VILLE CHAR(20) NOT NULL,
		PAYS CHAR(20) NOT NULL
	);

CREATE TABLE assoc.COMMANDE (
		CODE INTEGER NOT NULL,
		ID_ADH  CHAR(20) NOT NULL,
<<<<<<< HEAD
		QUANTITE INTEGER NOT NULL,
		date_commande DATE NOT NULL
=======
		QUANTITE DOUBLE NOT NULL,
		DATE_COMMANDE DATE NOT NULL
>>>>>>> 41ff946a69520d6fb79c9e9e7370c164a4ceae0d
	);
	drop table assoc.COMMANDE;
		
ALTER TABLE assoc.ADHERANT ADD CONSTRAINT pk PRIMARY KEY (ID_ADH);

ALTER TABLE assoc.COMMANDE ADD CONSTRAINT pk_commande PRIMARY KEY (ID_ADH,CODE);

ALTER TABLE assoc.COMMANDE ADD CONSTRAINT ID_ADH FOREIGN KEY (ID_ADH)
	REFERENCES assoc.ADHERANT (ID_ADH);

ALTER TABLE assoc.COMMANDE ADD CONSTRAINT CODE FOREIGN KEY (CODE)
	REFERENCES assoc.CATALOGUE (CODE);
	
	
	
	
	
	--INITIALISATION--
<<<<<<< HEAD

>>>>>>> 41ff946a69520d6fb79c9e9e7370c164a4ceae0d
=======
insert into "ASSOC"."ADHERANT" ("ID_ADH", "MDP", "NOM", "PRENOM", "ADRESSE", "CP", "VILLE", "PAYS") values('1', '1234', 'lecoq', 'gildas', '2 rue des pommes', '44000', 'nantes', 'france');
>>>>>>> c2729d34aacc5b7c92b6950c77bb6e80108dfc57
