--<ScriptOptions statementTerminator=";"/>
     --drop table assoc.CATALOGUE;
     --drop table assoc.ADHERANT;
     --drop table assoc.COMMANDE;
CREATE TABLE assoc.CATALOGUE (
		CODE INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		NOM CHAR(20) NOT NULL,
		PRIX DOUBLE NOT NULL,
		STOCK INTEGER NOT NULL
	);
	
CREATE TABLE assoc.ADHERANT (
		ID_ADH CHAR(20) NOT NULL,
		MDP CHAR(20) NOT NULL,
		NOM CHAR(20) NOT NULL,
		PRENOM CHAR(20) NOT NULL,
		ADRESSE CHAR(60) NOT NULL,
		CP CHAR(5) NOT NULL,
		VILLE CHAR(20) NOT NULL,
		PAYS CHAR(20) NOT NULL
	);

CREATE TABLE assoc.COMMANDE (
		CODE INTEGER,
		ID_ADH  CHAR(20) NOT NULL,
		QUANTITE DOUBLE NOT NULL,
		DATE_COMMANDE DATE NOT NULL
	);

CREATE INDEX SQL140129140246650 ON COMMANDE (CODE ASC);

CREATE UNIQUE INDEX SQL140129135514500 ON ADHERANT (ID_ADH ASC);

CREATE INDEX SQL140129140246651 ON COMMANDE (ID_ADH ASC);

CREATE UNIQUE INDEX SQL140129135643580 ON CATALOGUE (CODE ASC);

ALTER TABLE assoc.ADHERANT ADD CONSTRAINT pk PRIMARY KEY (ID_ADH);


ALTER TABLE assoc.COMMANDE ADD CONSTRAINT ID_ADH FOREIGN KEY (ID_ADH)
	REFERENCES assoc.ADHERANT (ID_ADH);

ALTER TABLE assoc.COMMANDE ADD CONSTRAINT CODE FOREIGN KEY (CODE)
	REFERENCES assoc.CATALOGUE (CODE);
	
	
	
	